### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by V-Laeda** [mageddo-projects/linux-bluetooth-connection-fix#2]
That what I recieve in console:
``` bash
➤ bluetoothctl devices
Device C0:86:B3:D6:1A:3F OpenRun Pro by Shokz
➤ java -jar linux-bluetooth-connection-fix-0.1.1-all.jar C0:86:B3:D6:1A:3F
Exception in thread "main" com.mageddo.commons.exec.ExecutionValidationFailedException: error, code=1, error=Ошибка подключения: Соединение отвергнуто
Произошла ошибка при выполнении pa_context_connect(): Соединение отвергнуто

	at com.mageddo.commons.exec.CommandLines$Result.checkExecution(CommandLines.java:73)
	at com.mageddo.linux.bluetoothfix.BluetoothConnector.isSoundDeviceConfigured(BluetoothConnector.java:162)
	at com.mageddo.linux.bluetoothfix.BluetoothConnector.connect(BluetoothConnector.java:23)
	at com.mageddo.linux.bluetoothfix.Main.main(Main.java:12)
➤ echo $?
1
```

**Comment by mageddo** [comment]
Your distro is not allowing the program to run "pactl list | grep 'Sink'" by security reasons,  not sure why and how to fix that. 

Have you tried to run as root?

**Comment by naxil** [comment]
hello.. i wan't open a new issue.. for me works.. ask me a root password and after it connect e reconnect many times the same headphone...
